### PR TITLE
Attempts to fix issue #3 by including FreeNAS' pySMART as a submodule…

### LINKED ISSUE #3: pySMART lacks Python 3.8 compatibility
When having `pySMART` installed from PyPI (via `pip`), server start fails with the following error message:
```
Aug 25 19:38:01 VM-Bullseye python3[3322]: Traceback (most recent call last):
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/mnt/dietpi_userdata/htpc-manager/Htpc.py", line 269, in <module>
Aug 25 19:38:01 VM-Bullseye python3[3322]:     main()
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/mnt/dietpi_userdata/htpc-manager/Htpc.py", line 266, in main
Aug 25 19:38:01 VM-Bullseye python3[3322]:     start()
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/mnt/dietpi_userdata/htpc-manager/htpc/server.py", line 191, in start
Aug 25 19:38:01 VM-Bullseye python3[3322]:     logger.info("Starting up webserver")
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
Aug 25 19:38:01 VM-Bullseye python3[3322]:     self._log(INFO, msg, args, **kwargs)
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/usr/lib/python3.8/logging/__init__.py", line 1565, in _log
Aug 25 19:38:01 VM-Bullseye python3[3322]:     fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
Aug 25 19:38:01 VM-Bullseye python3[3322]: TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
```
The reason is that `pySMART` overrides the `findCaller` function in a way that is not Python 3.8 compatible. There is an upstream fix available: https://github.com/freenas/py-SMART/commit/c5d6aabc80854ef27d9a7e4c4b2828478db5bf9d
But it has not yet been uploaded to the PyPI repository: https://pypi.org/project/pySMART/

### PR DESCRIPTION
**Pull request by gmiranda**
…. Note that this has some implications when cloning (https://git-scm.com/book/en/v2/Git-Tools-Submodules)

### CODE REVIEW

**Comment by MichaIng** [comment]
Nice I'll test it tomorrow.

First I was thinking, why not use `libs/pySMART` as submodule path, but we need the included pySMART subdirectory to be inside `libs` and not the repo root directory. Then I have no better idea either, if we don't want to literally copy the code into our repo, which would mean to sync updates manually as well. As fast as PyPI got the update, we can revert.

**Comment by MichaIng** [comment]
Okay, first of all having pySMART in that dir + symlink works fine. But the problem is that `git clone` does not automatically pull submodules without using the `--recurse-submodules` option. So it would break installers which use `git clone` + `pip3 install -r requirements.txt` and expect pySMART to be install with this.
_EDIT: The submodule is missing as well when downloading the archive manually: https://github.com/gmiranda/HTPC-Manager/archive/issue_3.tar.gz_

When user see in turn the SMART module not functional and HTPC-Manager throwing the log `modules.stats :: ERROR :: No module named 'pySMART'`, running `pip install pySMART` would then cause the complete service/process to crash on start. Realising that the intention was a submodule in the Git repo with un-released master branch and how to pull that it probably not that trivial for everyone.

I hence suggest to add the module statically until a new release is uploaded to PyPI. License-wise ([LGPL](https://github.com/truenas/py-SMART/blob/master/LICENSE)) there is not an issue with this. Each file has the copyright license and it is clearly added as separate library.

Btw, `workerpool` can be removed instead and replaced by a `requirements.txt` entry (which is the exact same version, that has never been updated): https://pypi.org/project/workerpool/
But no idea where `torrentsearch` (ts) is coming from.

**Comment by MichaIng** [comment]
Is [this](https://github.com/truenas/py-SMART/issues/35#issuecomment-842407226) an alternative, to directly use the current Git master branch in our `requirements.txt`?
```
git+https://github.com/truenas/py-SMART#egg=pySMART
```

**Comment by gmiranda** [comment]
> 
> 
> Is [this](https://github.com/truenas/py-SMART/issues/35#issuecomment-842407226) an alternative, to directly use the current Git master branch in our `requirements.txt`?
> 
> ```
> git+https://github.com/truenas/py-SMART#egg=pySMART
> ```

Have you tried it?
I get this error:
`2021-06-20 13:22:21 :: modules.stats :: ERROR :: Error Pulling S.M.A.R.T. data 'Device' object has no attribute 'supports_smart'
Traceback (most recent call last):
  File "/home/hefe/HTPC-Manager/modules/stats.py", line 595, in smart_info
    'supports_smart': hds.supports_smart,
AttributeError: 'Device' object has no attribute 'supports_smart'
`

**Comment by MichaIng** [comment]
Works fine here, tested on Debian Buster (Python 3.7) and Bullseye (Python 3.9). But this was on VMs, so S.M.A.R.T. data cannot be read. Testing on  physical machine...

... jep can confirm issue on notebook 🤔.

It seems like this attribute was never there: https://github.com/truenas/py-SMART/blob/master/pySMART/device.py
And I guess older Python version just ignored that fact? `smart_capable` or `smart_enabled` seems to be the attribute we actually want: https://github.com/truenas/py-SMART/blob/master/pySMART/device.py#L121-L130

**Comment by MichaIng** [comment]
Replacing `supports_smart` with `smart_enabled` here works fine and the widget + menu works very well: https://github.com/HTPC-Manager/HTPC-Manager/blob/master2/modules/stats.py#L595

I only wonder where it is actually used. It is not part of the info table and not processed in the related script: https://github.com/HTPC-Manager/HTPC-Manager/blob/master2/interfaces/default/js/stats.js#L325-L332

I removed line 595 from `stats.py` and all works fine. Of course capability and whether enabled or not could be used to show a more meaningful message than "SMART is not probably configured", like:
- smartmontools are not installed
- This drive does not support S.M.A.R.T.
- This drive supports S.M.A.R.T. but has it disabled

I vote for removing the line for now until someone finds time to implement processing additional info provided by pySMART in a reasonable way.

**EDIT: #25**
With this and installing the current master pySMART via requirements.txt works pretty fine on all my tests. I vote for that solution, which is also easier to revert, once a stable release to PyPI has been done.

**Comment by MichaIng** [comment]
Alternative: https://pypi.org/project/pySMART.naudit/
While the original project keeps merging pull requests from the Naudit fork (just yesterday), it's a bit strange that no upload to PyPI is done, even that it's currently broken with Python > 3.7. Probably the maintainer who merges the PRs is not the one that has access to the PyPI project.

Benefit of the Naudit release it that it ships an elevated version string while using the raw GitHub source somehow ends up with an 0.3 version (even that that code is new), which might confuse and `pip3 install -U pySMART` hence downgrades it.

**Comment by MichaIng** [comment]
Issue solved, the maintainer of the fork became official maintainer of the FreeNAS repo and PyPI build: https://github.com/truenas/py-SMART/issues/20#issuecomment-878920618

Update on PyPI planned today: https://pypi.org/project/pySMART/

Shall we add a minimum version to the requirements file?

**Comment by MichaIng** [comment]
Release done, running tests...

**Comment by gmiranda** [comment]
Sorry for not replying earlier, I'm rather busy and have been unable to
have a look at this issue.

**Comment by MichaIng** [comment]
No worries, we both didn't agree into any obligations 🙂. I now put this onto higher priority for myself as Debian Bullseye with Python 3.9 is about to be released and I want HTPC-Manager ready for our _DietPi_ distribution to have stable Bullseye-based images 🙂.

**Comment by MichaIng** [comment]
Looks like the new pySMART release broke Python 3.9 support at another place:
```
AttributeError: 'Logger' object has no attribute 'trace'
```
Strange is that according to the documentation, that logging level never existed (debug instead) while that was used in pySMART for more than five years already 🤔: https://docs.python.org/3.7/howto/logging.html

It was suggested here, but never added: https://github.com/python/cpython/pull/3930
I'm confused.

**EDIT: Ah, defined here: https://github.com/truenas/py-SMART/blob/master/pySMART/utils.py#L31**

**EDIT2: Jep a bug, fixed with: https://github.com/truenas/py-SMART/pull/41**
Let's hope for a quick hotfix release.

**Comment by MichaIng** [comment]
Fix merged and released already. I mark this issue as closed. Also piwheels.org built those releases already: https://piwheels.org/project/pysmart/

**Pull request closed without merging**
