### PR TITLE
Add Watcher3 module

### PR DESCRIPTION
**Pull request by MichaIng**
@scambra
I found your fork which support for Watcher3 movie NZB & Torrent searcher and snatcher. Do you still use HTPC Manager and would you mind to contribute this to our new Python 3 orga fork?

Probably some minor changes to the existing code are required to make it compatible with Python 3, but otherwise it looks good.

### CODE REVIEW

**Comment by scambra** [comment]
Yes, Iḿ still using it, I would like to get it merged, although I won't have time to make any change in few weeks probably

**Comment by MichaIng** [comment]
That is great and no rush required. As I opened the PR, do you have the option to enable file edits by maintainers? Then I could do some formal adjustments, check and fix Python 3 compatibility, satisfy CodeFactor and so, when I find time.

**Comment by scambra** [comment]
I don't see option to allow edits from maintainers

**Comment by MichaIng** [comment]
Okay, I think then you'd need to open the PR here to make this possible. I mark this one as closed, else I think GitHub denies a new PR with same branches involved.

**Pull request closed without merging**
